### ISSUE TITLE
Create "who we are" page    

### ISSUE THREAD

**Issue by liessdow** [czqoocavatsim/web#171]
Title, `resources/views/about/who-we-are.blade.php`

**Comment by dsolesvik** [comment]
Can this be pasted from https://ganderoceanic.ca/about/who-we-are, or is it a completely new text?

**Comment by lieseld** [comment]
> Can this be pasted from https://ganderoceanic.ca/about/who-we-are, or is it a completely new text?

It's whatever you all want it to be rather than me being uncreative, so feel free to copy the old content and adjust

**Comment by dsolesvik** [comment]
@andrewogden1678 Let me know if copying the old content is fine with you, if not, I'll be more than happy to write a new "who we are" page.
