### ISSUE TITLE
API gives 500

### ISSUE THREAD

**Issue by daniluk4000** [czqoocavatsim/web#263]
Hey there! I wanted to make great integration of tracks into my new radar service, but sadly all API methods give 500: https://tracks.ganderoceanic.ca/data

Am I doing something wrong?

**Comment by mufassilyasir** [comment]
Hello, indeed it does return 500. Please use [Natrak API](https://nattrak.vatsim.net/api/tracks) instead.

**Comment by daniluk4000** [comment]
Thanks <3
