### ISSUE TITLE
Instructor Students Attachments

### ISSUE THREAD

**Issue by mufassilyasir** [czqoocavatsim/web#297]
When an active student is removed, their corresponding row should be deleted from the instructor_students table. This ensures that the student no longer appears in the instructor's profile.

**Comment by mufassilyasir** [comment]
Is this already solved in https://github.com/czqoocavatsim/web/pull/296/commits/df225f3d996717a481c6659b0765e955927cc0ff ?

**Comment by JoshuaMicallefYBSU** [comment]
Following occurs:
- Certify Student: Instructor is unassigned, and status is set as false.
```
        $instructor_link = InstructorStudentAssignment::where('student_id', $cid);
        $instructor_link->delete();```
- Remove Student: Instructor is unassigned, and status is set as false
```
$links = InstructorStudentAssignment::where('student_id', $student->id);
        foreach ($links as $l) {
            $l->delete();
        }
```

I assume this is what you mean. Just let me know if you meant this or something else :)

**Comment by JoshuaMicallefYBSU** [comment]
This has been resolved.
