### ISSUE TITLE
Controller Activety

### ISSUE THREAD

**Issue by Verbjimtim** [czqoocavatsim/web#298]
A log of when controllers logon to the network under our region
similar to [Vatcan](https://discord.com/channels/567549256357904405/1202015885641121852)
maybe even it editing when they logoff with a total logged on time

**Comment by JoshuaMicallefYBSU** [comment]
This has been implemented.

However, the decision needs to be made to either leave it as is, or have a single message that is updated whenever controllers log on/off.
